#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RunningAssistant.Resource", IsApplication=true)]

namespace RunningAssistant
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int blue = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int highlight = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int lightgrey = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int thickblueline = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int thinblueline = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int Distance = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int DistanceHeader = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int MinutesText = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int SecondsText = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int Text = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int Time = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int TimeHeader = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int aboutButton = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int calculateButton = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int distanceText = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int hoursText = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int resultsListView = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int showPaceCalculatorButton = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Calculator = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SplitItemView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
